### ISSUE TITLE
New feature: Dynamic target_energy

### ISSUE THREAD

**Issue by grotteru** [epaulsen/energytariff#7]
First of all, I love this integration.

I have a suggestion for an improvement. In my case i usually end up in with the tariff for 5-10kWh capacity, especially during winter. But for spring, summer and autumn i try to stay within 2-5kWh. I think there are many in the same situation who has automations set up to keep within certain limits. 

Would it be possible to have the option to have the _target_energy_ set to the _threshold_ set in _levels_? For example: If my average peak kWh is 4,8kWh and I have defined a level with threshold 5kWh the _target_energy_ should be 5kWh. If I later the same month reach an average of 5,8 kWh and the next level threshold is 10kWh the _target_energy_ change to 10kWh.

I think its nice that it is possible to set a constant target_energy so this has to be an an extra option.

I would love to try to fix it myself but I dont have a lot of spare time.

**Comment by epaulsen** [comment]
@grotteru , thanks for the kind words.
I do believe that this is already built-in, simply remove/comment out  the `target_energy` from your configuration.

From the documentation on the `Available power this hor sensor`: 

_"If `target_energy` setting is configured, this value is used as a threshold. Otherwise, if level setting is configured, the current energy level threshold value is used. If neither are configured, this sensor is unavailable."_

**Note:** The target_energy configuration setting was added because the sensor for available power will behave somewhat erratic on days 1 and 2 of a month.  On day 1, it will start with the assumption that you should not exceed lowest level(in my case 0-2 kWh), which caused a lot of automations turning off everything in my house after midnight, trying to use below 2 kWh of energy.  As the day went by, it stabilized on level 5-10.  But when we rolled in to day 2 of the month, the average becomes calculated as a value of highest on day 1 and 2, resulting in current capacity level dropping to 2-5, and automations(again) turning off both heating, EV charging and water heating to stay below 5 kWh.  After that I added the `target_energy` configuration setting 😄 

Let me know if that fixes your issue.  If it does, please close the issue.

**Comment by grotteru** [comment]
Sorry, my bad not reading the documentation properly. 

I will close the issue.
